### ISSUE TITLE
Is ETCD backend ready for release?

### ISSUE THREAD

**Issue by debarshri** [chartmuseum/storage#11]
I do see the etcd support in the master. Is there going to be tagged release for that version that could be used in the chartmuseum project?

**Comment by jdolitsky** [comment]
@debarshri etcd support has been released in 0.4.0, please let us know if you run into any issue. Thanks!

**Comment by debarshibasak** [comment]
I would create a pull request chartmuseum project to add support for etcd as I need the same for one of our project. I would let you know if I run into any issues. Thanks.
