### ISSUE TITLE
The azure storage does not support other region but core.windows.net

### ISSUE THREAD

**Issue by williamfeng323** [chartmuseum/storage#14]
We are hoping to deploy the chartmuseum in our China Azure environment. However, it does not support us to do so due to it is calling NewBasicClient instead of NewClient in [this line](https://github.com/chartmuseum/storage/blob/master/microsoft.go#L44)

**Comment by jdolitsky** [comment]
@williamfeng323 thanks for opening. We should add new option `--storage-microsoft-endpoint`

can pass that value as the `serviceBaseURL` here https://github.com/Azure/azure-sdk-for-go/blob/master/storage/client.go#L296
