### ISSUE TITLE
feature: support for minio server 

### ISSUE THREAD

**Issue by rugwirobaker** [chartmuseum/storage#20]
I love using minio as a self hosted alternative to aws s3. Seeing as chartmuseum storage makes the whole thing even easier I really would love to make a pr for minio storage interface implementation.

**Comment by jdolitsky** [comment]
Hello, this is actually already possible by overriding the S3 endpoint when constructing an S3 backend: https://github.com/chartmuseum/storage/blob/master/amazon.go#L45
