### ISSUE TITLE
ETCD error:  chart LastModified using ModRevision

### ISSUE THREAD

**Issue by guoweikuang** [chartmuseum/storage#25]
Is it reasonable to use ModRevision as LastModified for etcd? ModRevison's explanation is: mod_revision is the revision of last modification on this key.

![屏幕快照 2019-09-17 下午8 01 01](https://user-images.githubusercontent.com/12684035/65039962-f3763980-d985-11e9-8104-8e91d279fbfb.png)

**Comment by jdolitsky** [comment]
@guoweikuang thank you for opening

**Comment by jdolitsky** [comment]
ping @yylt (original author of the etcd support) - any ideas?

**Comment by guoweikuang** [comment]
@jdolitsky 
I can't think of any good solution for the time being. Do you have any suggestions?

**Comment by yylt** [comment]
Hi @guoweikuang 
I'm confused about what you expected? could you explain what wrong with `craeted` time.

**Comment by guoweikuang** [comment]
@yylt This created time is incorrect and does not indicate the time the Chart was stored in the chartmuseum.  I expect this created time to be imported into the chartmuseum. 
As shown below,
<img width="654" alt="屏幕快照 2019-10-10 下午3 20 28" src="https://user-images.githubusercontent.com/12684035/66547429-cb878980-eb71-11e9-9c64-77f1f1933334.png">

**Comment by yylt** [comment]
@guoweikuang  thank your suggestion！

`ModRevision` is just ordered index, it should not as `LastModified` 

maybe it could use key `{path}/timestamp` to save update time
