### ISSUE TITLE
New release to gain latest AWS SDK with IAM roles via Service Accounts 

### ISSUE THREAD

**Issue by andyspiers** [chartmuseum/storage#32]
Hi,

Is there any chance you could make a new release of this project please?

I would like to get chartmuseum to support getting its AWS credentials from IAM roles attached to the Service Accounts. This was already implemented in #27 but needs releasing before chartmuseum can update its dependencies in https://github.com/helm/chartmuseum/blob/master/go.mod#L10

Thanks!
Andy

**Comment by uLan08** [comment]
Hi @jdolitsky,

I would love to see this being released. I just tried out ChartMuseum v0.10.0 and expected for AWS credentials from IAM roles to work.

**Comment by andyspiers** [comment]
Happy new year! Any chance you could make a release of this project please @technosophos or @jdolitsky ?

**Comment by jdolitsky** [comment]
@andyspiers will look at soon, sorry for delay

**Comment by apenney** [comment]
Appreciate you looking, just stumbled over this after fighting for about an hour to get serviceAccounts/iam roles working in EKS for chartmuseum. Was very confused!

**Comment by bagel-dawg** [comment]
@jdolitsky I am also interested in this feature to be released.

**Comment by jdolitsky** [comment]
Hello all, v0.6.0 has been released with a bunch of dependency updates, including AWS. Thank you for your patience 
https://github.com/chartmuseum/storage/releases/tag/v0.6.0

Will be working towards getting this into a new CM release next
