### ISSUE TITLE
Object missing metadata fields to store the chart metadata information 

### ISSUE THREAD

**Issue by scbizu** [chartmuseum/storage#49]
Related to chartmuseum's [#22](https://github.com/helm/chartmuseum/issues/22) and [#220](https://github.com/helm/chartmuseum/issues/22) , we still have a bug of resolving chart deletion between cache and the storage , we temporarily fix it by treating the cache one as [no content chart file](https://github.com/helm/chartmuseum/blob/v0.12.0/pkg/repo/chart.go#L91) and [parsing the delete chart version by ourselves to find the correct version to delete](https://github.com/helm/chartmuseum/blob/v0.12.0/pkg/repo/chart.go#L102).

But parsing the version correctly is hard even if the stored chart version is non-semver , I raise a [pr#363](https://github.com/helm/chartmuseum/pull/362) to fix the issue but it can not cover all the cases. So I think parsing the delete version by ourselves maybe is not the right way to fix this issue.

The root cause of this issue is the **storage.Object can not store the metadata of our chart file** , if we can add the such field into the `storage.Object`, the issue can be fixed in the right way .

/cc @jdolitsky , if ok , I can work on another PR to fix this issue .

**Comment by jdolitsky** [comment]
@scbizu - sure, this sounds good to add more meta to Object type

**Comment by jdolitsky** [comment]
now in v0.10.0
